const CONSTANTS = {
  'ACCESS_TOKEN' : 'MTQzMTU5NDozNDYwMDMzMjEyODAwNTg4OTQ6OTIyMzM3MjAzNjg1NDc3NTgwN3wxNDYyNjQ4NDk1OjI1OTIwMDAtLWE2YzgyMWQyOTQ2MjViODk5ZjI5YTE3Y2U4MTBiYjM4'
};

export default CONSTANTS;
